<?php
declare(strict_types=1);

return [
    'caister-mews' => [
        'slug' => 'caister-mews', 'intent' => 'rent', 'status' => 'To let', 'title' => 'Caister Mews',
        'area' => 'Balham', 'postcode' => 'SW12', 'price' => 2850, 'price_label' => '&pound;2,850 pcm',
        'bedrooms' => 2, 'bathrooms' => 1, 'receptions' => 1, 'type' => 'Mews house',
        'image' => '/assets/property-1-ref.jpg', 'tenure' => 'Freehold', 'council_tax' => 'Band E',
        'epc' => 'C', 'floor_area' => '824 sq ft / 76.6 sq m', 'reference' => 'GPS-10482',
        'summary' => 'A bright two-bedroom mews home to rent within a quiet gated development moments from Balham High Road.',
        'description' => [
            'This thoughtfully presented mews house offers well-balanced living space across two floors. The ground floor centres around an open-plan kitchen and reception room, with direct access to a private courtyard that is ideal for relaxed entertaining.',
            'Upstairs are two comfortable double bedrooms and a contemporary family bathroom. The property combines a tucked-away setting with excellent access to Balham station, local shops, cafés and green spaces.',
        ],
        'features' => ['Two double bedrooms', 'Private gated mews', 'Open-plan kitchen and reception', 'Private courtyard', 'Excellent transport connections', 'Professionally managed'],
    ],
    'upper-tooting-road' => [
        'slug' => 'upper-tooting-road', 'intent' => 'rent', 'status' => 'To let', 'title' => 'Upper Tooting Road',
        'area' => 'Tooting', 'postcode' => 'SW17', 'price' => 2200, 'price_label' => '&pound;2,200 pcm',
        'bedrooms' => 2, 'bathrooms' => 2, 'receptions' => 1, 'type' => 'Apartment',
        'image' => '/assets/property-2-ref.jpg', 'tenure' => 'Leasehold', 'council_tax' => 'Band D',
        'epc' => 'B', 'floor_area' => '905 sq ft / 84.1 sq m', 'reference' => 'GPS-10465',
        'summary' => 'A generous modern rental apartment with two bathrooms, a private balcony and superb access to Tooting Bec station.',
        'description' => ['Set within a contemporary development, this spacious apartment provides a large open-plan living area with full-height glazing and access to a private balcony.', 'Both bedrooms are well proportioned, with the principal bedroom benefiting from an en-suite shower room. Secure entry and excellent local amenities make this an appealing rental home.'],
        'features' => ['Two double bedrooms', 'Two bathrooms', 'Private balcony', 'Secure modern development', 'Close to Tooting Bec Underground', 'Managed tenancy'],
    ],
    'balham-high-road-apartment' => [
        'slug' => 'balham-high-road-apartment', 'intent' => 'rent', 'status' => 'To let', 'title' => 'Balham High Road',
        'area' => 'Balham', 'postcode' => 'SW12', 'price' => 1650, 'price_label' => '&pound;1,650 pcm',
        'bedrooms' => 2, 'bathrooms' => 1, 'receptions' => 1, 'type' => 'Apartment',
        'image' => '/assets/property-3-ref.jpg', 'tenure' => 'Long let', 'council_tax' => 'Band C',
        'epc' => 'C', 'floor_area' => '690 sq ft / 64.1 sq m', 'reference' => 'GPS-L2196',
        'summary' => 'A well-located two-bedroom apartment offering bright interiors and immediate access to Balham amenities.',
        'description' => ['The apartment offers a bright reception room, separate fitted kitchen, two bedrooms and a modern bathroom. Neutral finishes make it easy to settle in and make the space your own.', 'Balham station, supermarkets and an excellent choice of independent cafés and restaurants are all within easy reach.'],
        'features' => ['Two bedrooms', 'Separate fitted kitchen', 'Central Balham location', 'Part furnished', 'Available immediately', 'Professionally managed'],
    ],
    'balham-high-road-one-bed' => [
        'slug' => 'balham-high-road-one-bed', 'intent' => 'buy', 'status' => 'For sale', 'title' => 'Balham High Road',
        'area' => 'Balham', 'postcode' => 'SW12', 'price' => 350000, 'price_label' => '&pound;350,000',
        'bedrooms' => 1, 'bathrooms' => 1, 'receptions' => 1, 'type' => 'Apartment',
        'image' => '/assets/property-4-ref.jpg', 'tenure' => 'Leasehold', 'council_tax' => 'Band C',
        'epc' => 'C', 'floor_area' => '515 sq ft / 47.8 sq m', 'reference' => 'GPS-10431',
        'summary' => 'A smart one-bedroom apartment in the heart of Balham, ideal for a first-time buyer or investor.',
        'description' => ['This attractive apartment features an open-plan reception and kitchen, a generous double bedroom and a modern bathroom.', 'Its central position places Balham Underground and National Rail services, shops and restaurants moments from the front door.'],
        'features' => ['One double bedroom', 'Open-plan living space', 'Central location', 'Long lease', 'Ideal first purchase', 'Strong rental potential'],
    ],
    'bedford-hill-house' => [
        'slug' => 'bedford-hill-house', 'intent' => 'buy', 'status' => 'For sale', 'title' => 'Bedford Hill',
        'area' => 'Balham', 'postcode' => 'SW12', 'price' => 825000, 'price_label' => '&pound;825,000',
        'bedrooms' => 3, 'bathrooms' => 2, 'receptions' => 2, 'type' => 'Terraced house',
        'image' => '/assets/property-1-ref.jpg', 'tenure' => 'Freehold', 'council_tax' => 'Band F',
        'epc' => 'D', 'floor_area' => '1,284 sq ft / 119.3 sq m', 'reference' => 'GPS-10491',
        'summary' => 'A characterful three-bedroom home with two reception rooms and a south-facing garden near Tooting Bec Common.',
        'description' => ['Period detail and practical family space come together in this attractive Balham house. Two reception rooms and an extended kitchen create flexible ground-floor accommodation.', 'Three bedrooms, two bathrooms and a private rear garden complete a home positioned for schools, transport and nearby green space.'],
        'features' => ['Three bedrooms', 'Two reception rooms', 'South-facing garden', 'Extended kitchen', 'Period character', 'Near Tooting Bec Common'],
    ],
    'tooting-bec-road' => [
        'slug' => 'tooting-bec-road', 'intent' => 'buy', 'status' => 'For sale', 'title' => 'Tooting Bec Road',
        'area' => 'Tooting', 'postcode' => 'SW17', 'price' => 725000, 'price_label' => '&pound;725,000',
        'bedrooms' => 3, 'bathrooms' => 1, 'receptions' => 2, 'type' => 'Terraced house',
        'image' => '/assets/property-2-ref.jpg', 'tenure' => 'Freehold', 'council_tax' => 'Band E',
        'epc' => 'D', 'floor_area' => '1,116 sq ft / 103.7 sq m', 'reference' => 'GPS-10473',
        'summary' => 'A handsome period house with flexible living space, a private garden and excellent Underground access.',
        'description' => ['The property retains period proportions while offering scope for a new owner to personalise. The ground floor includes two reception areas, a fitted kitchen and access to a private garden.', 'Three bedrooms and a family bathroom occupy the upper floor, with local schools and transport close by.'],
        'features' => ['Three bedrooms', 'Two reception areas', 'Private rear garden', 'Freehold', 'Potential to extend subject to consent', 'Close to Underground'],
    ],
    'ravenslea-road' => [
        'slug' => 'ravenslea-road', 'intent' => 'rent', 'status' => 'To let', 'title' => 'Ravenslea Road',
        'area' => 'Balham', 'postcode' => 'SW12', 'price' => 2400, 'price_label' => '&pound;2,400 pcm',
        'bedrooms' => 2, 'bathrooms' => 2, 'receptions' => 1, 'type' => 'Maisonette',
        'image' => '/assets/property-3-ref.jpg', 'tenure' => 'Long let', 'council_tax' => 'Band D',
        'epc' => 'C', 'floor_area' => '812 sq ft / 75.4 sq m', 'reference' => 'GPS-L2210',
        'summary' => 'A beautifully finished two-bedroom maisonette with a private garden on a popular residential road.',
        'description' => ['Arranged with a spacious open-plan living area and direct garden access, this maisonette is designed for easy modern living.', 'Two double bedrooms and two bathrooms provide flexibility for sharers, a couple or a small family.'],
        'features' => ['Two double bedrooms', 'Two bathrooms', 'Private garden', 'Modern finish', 'Unfurnished', 'Available this month'],
    ],
    'streatham-commercial' => [
        'slug' => 'streatham-commercial', 'intent' => 'commercial', 'status' => 'To let', 'title' => 'Streatham High Road',
        'area' => 'Streatham', 'postcode' => 'SW16', 'price' => 45000, 'price_label' => '&pound;45,000 pa',
        'bedrooms' => 0, 'bathrooms' => 1, 'receptions' => 0, 'type' => 'Retail premises',
        'image' => '/assets/property-4-ref.jpg', 'tenure' => 'New lease', 'council_tax' => 'Business rates apply',
        'epc' => 'C', 'floor_area' => '1,425 sq ft / 132.4 sq m', 'reference' => 'GPS-C309',
        'summary' => 'A prominent ground-floor commercial unit with strong frontage on a busy South London high street.',
        'description' => ['The unit provides open retail space, rear storage, staff facilities and a prominent glazed frontage.', 'Suitable for a range of commercial uses subject to the necessary consents and offered on a new lease by negotiation.'],
        'features' => ['Prominent high-street frontage', 'Open retail area', 'Rear storage', 'Staff facilities', 'New lease available', 'Flexible commercial potential'],
    ],
];
