@extends('layouts.store')
@section('title', 'Contact Us | Gani Property Services')
@php($activePage = 'contact')
@section('content')
<main id="top">
    <section class="page-banner contact-banner" aria-labelledby="contact-page-title"><div class="page-banner-shade"></div><div class="page-banner-content"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><span>/</span><span>Contact</span></nav><p class="eyebrow eyebrow-light">WE ARE HERE TO HELP</p><h1 id="contact-page-title">Let us talk property</h1><p>Tell us what you need and our Balham team will point you in the right direction.</p></div></section>
    <section class="contact-layout section">
        <div class="contact-details"><p class="eyebrow">GET IN TOUCH</p><h2>Start a conversation with our local team</h2><p>Whether you are looking for a rental, letting a property, exploring guaranteed rent or need management advice, we would be pleased to hear from you.</p><div class="contact-methods"><article><span><svg><use href="#icon-phone"/></svg></span><div><small>Call us</small><a href="tel:02086737778">020 8673 7778</a></div></article><article><span><svg><use href="#icon-whatsapp"/></svg></span><div><small>WhatsApp us</small><a href="https://wa.me/447828454111" aria-label="WhatsApp +44 7828 454111">+44 7828 454111</a></div></article><article><span><svg><use href="#icon-chat"/></svg></span><div><small>Email us</small><a href="mailto:hello@ganipropertyservices.co.uk">hello@ganipropertyservices.co.uk</a></div></article><article><span><svg><use href="#icon-pin"/></svg></span><div><small>Visit us</small><p>142 Balham High Road<br>London SW12 9BW</p></div></article><article><span><svg><use href="#icon-check"/></svg></span><div><small>Opening hours</small><p>Mon-Fri: 9am-6pm<br>Sat: 9am-4pm</p></div></article></div></div>
        <div class="contact-form-panel"><div class="contact-form-heading"><p class="eyebrow">SEND AN ENQUIRY</p><h2>How can we help?</h2><p>Complete the form and a member of our team will get back to you.</p></div><form class="contact-form" action="mailto:hello@ganipropertyservices.co.uk" method="post" enctype="text/plain"><div class="form-row"><label class="form-field"><span>Your name</span><input type="text" name="name" autocomplete="name" required></label><label class="form-field"><span>Email address</span><input type="email" name="email" autocomplete="email" required></label></div><div class="form-row"><label class="form-field"><span>Phone number</span><input type="tel" name="phone" autocomplete="tel"></label><label class="form-field"><span>I am interested in</span><select name="interest" required><option value="">Please select</option>@foreach(['Renting', 'Letting', 'Property management', 'Guaranteed rent', 'Other'] as $option)<option value="{{ $option }}" @selected($interest === $option)>{{ $option }}</option>@endforeach</select></label></div><label class="form-field"><span>Your message</span><textarea name="message" rows="6" maxlength="3000" required>{{ $message }}</textarea></label><p class="form-privacy">By submitting this form, you agree that Gani Property Services may use your details to respond to your enquiry.</p><button class="button" type="submit">Send enquiry</button></form></div>
    </section>
    <section class="contact-valuation"><div><p class="eyebrow eyebrow-light">PREFER TO TALK?</p><h2>Visit us on Balham High Road</h2><p>Drop into our office or call the team for friendly, practical property advice.</p></div><a class="button button-white" href="tel:02086737778">Call 020 8673 7778</a></section>
</main>
@endsection
